#// vim: set ft=ansible:
---
- name: playbook with common tasks for all hosts
  hosts: all

  tasks:
      - name: update and upgrade apt packages
        apt: >
            upgrade=yes
            update_cache=yes
            cache_valid_time=3600
        become: true
