#// vim: set ft=ansible:
---
- name: prereq playbook for nodes
  hosts: nodes
  become: yes
  tasks:
    - name: http proxy for apt
      lineinfile:
        create: yes
        dest: /etc/apt/apt.conf.d/10proxy
        line: Acquire::http::Proxy "http://192.168.31.1:8888/";
        state: present
